#!/usr/bin/env python3
"""org-setup --prune: rewrite role settings.local.json from permissions.md.

Background (Issue #88): the additive ``/org-setup`` cannot remove stale or
broadened entries from ``settings.local.json``. This tool rewrites the file
from the role template embedded in
``.claude/skills/org-setup/references/permissions.md`` (the human-readable
projection of ``tools/role_configs_schema.json``) so drift is fully resolved.

User-extension protection (Issue #88 option A): if a sibling
``settings.local.override.json`` exists, its contents are deep-merged on top
of the template. Users put bespoke entries there once; the prune tool never
touches it, so personal customizations survive every rewrite.

Targets: secretary / dispatcher / curator. (worker is generated by
org-delegate -- out of scope here.)

``user_common`` (``~/.claude/settings.json``) lives in the user's home and is
shared with non-org plugins, so the prune rewrite would clobber unrelated
keys. Instead a dedicated mode -- ``--user-common-sandbox`` -- performs only
a *targeted, idempotent union merge* into the user-level sandbox block:

- ``sandbox.filesystem.denyRead`` for sensitive credential directories
  (existence-checked + realpath-escape skipped on WSL; ``~``-prefixed
  literal entries preserved so the file stays portable across users).
- ``sandbox.filesystem.denyWrite`` for ``~/.claude/settings.json``
  (file literal, NOT existence-checked -- preventive deny so the write
  guard is in place before Claude Code first creates the file).

All other keys are passed through untouched. See Issue #429 for the
denyRead migration (Task B/C) and Issue #433 for the denyWrite migration
out of the shared, checked-in ``.claude/settings.json``.

Usage:
    py -3 tools/org_setup_prune.py --role secretary --dry-run
    py -3 tools/org_setup_prune.py --role dispatcher
    py -3 tools/org_setup_prune.py --all --dry-run
    py -3 tools/org_setup_prune.py --user-common-sandbox --dry-run
    py -3 tools/org_setup_prune.py --user-common-sandbox
"""

from __future__ import annotations

import argparse
import datetime as _dt
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_role_configs as _check  # noqa: E402  -- reuse validate_config

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SCHEMA = REPO_ROOT / "tools" / "org_extension_schema.json"
DEFAULT_PERMISSIONS_MD = (
    REPO_ROOT
    / ".claude"
    / "skills"
    / "org-setup"
    / "references"
    / "permissions.md"
)

PRUNABLE_ROLES = ("secretary", "dispatcher", "curator")

# Sensitive directories that should be added to user_common's
# ``sandbox.filesystem.denyRead`` so credentials are masked at the bwrap
# layer for every Claude pane spawned in this user's home (Issue #429).
# Stored as ``~``-prefixed *directory* literals so:
#   1. the file stays portable across users (no /home/<user>/ leak), and
#   2. bwrap mounts ``/dev/null`` over the whole directory -- masking the
#      directory listing too. A per-file deny (``~/.config/gh/hosts.yml``)
#      still leaves the parent directory readable, leaking neighbour
#      filenames; directory-unit denies close that gap.
USER_COMMON_SANDBOX_DENYREAD_CANDIDATES: tuple[str, ...] = (
    "~/.ssh",
    "~/.aws",
    "~/.config/gh",
    "~/.kube",
    "~/.gnupg",
    "~/.docker",
    "~/.config/aws-vault",
)

# Files (not directories) that should be added to user_common's
# ``sandbox.filesystem.denyWrite`` so writes to user-level Claude
# settings can never be made via Bash subprocess inside the bwrap
# sandbox (Issue #433 -- previously lived as a project-shared entry
# in ``.claude/settings.json`` until Task C migrated denyRead candidates
# to user_common; denyWrite is now migrated symmetrically).
#
# Stored as ``~``-prefixed *file* literals (portable across users), and
# **not existence-checked**: blocking a write is preventive and remains
# meaningful even when the file has not been created yet (fresh
# installs come in with ``~/.claude/settings.json`` absent, and we want
# the deny in place before Claude Code first writes it).
#
# Note: symmetric directory denyWrite for ``~/.ssh`` / ``~/.aws`` / etc.
# is intentionally **deferred** (Issue #433 scope) -- those would block
# legitimate writes (e.g. ``ssh-keygen``, ``aws configure``) without a
# clear threat model, and the denyRead candidates already mitigate the
# read-exfiltration vector that motivated Task B/C.
USER_COMMON_SANDBOX_DENYWRITE_CANDIDATES: tuple[str, ...] = (
    "~/.claude/settings.json",
)

DEFAULT_USER_COMMON_SETTINGS_PATH = Path.home() / ".claude" / "settings.json"


def load_schema(path: Path) -> dict:
    """Delegate to ``check_role_configs.load_schema`` so this tool sees
    the same framework-merged dict (Step B shim integration)."""
    return _check.load_schema(path)


def extract_role_blocks(md_text: str, roles: dict) -> dict[str, dict | None]:
    """Mirror of check_role_configs.extract_role_blocks (kept inline to avoid a
    cross-module import at script invocation time)."""
    results: dict[str, dict | None] = {}
    sections = re.split(r"(?m)^## ", md_text)
    for role_name, role_def in roles.items():
        marker = role_def.get("docs_section")
        if not marker:
            continue
        block = None
        for section in sections[1:]:
            if marker in section.splitlines()[0]:
                m = re.search(r"```json\n(.*?)\n```", section, re.DOTALL)
                if m:
                    block = json.loads(m.group(1))
                break
        results[role_name] = block
    return results


def role_settings_path(root: Path, role: str) -> Path:
    if role == "secretary":
        return root / ".claude" / "settings.local.json"
    if role == "dispatcher":
        return root / ".dispatcher" / ".claude" / "settings.local.json"
    if role == "curator":
        return root / ".curator" / ".claude" / "settings.local.json"
    raise ValueError(f"unsupported role for prune: {role!r}")


def override_path(settings_path: Path) -> Path:
    return settings_path.with_name("settings.local.override.json")


# ---------- placeholder resolution ----------

PLACEHOLDER_KEYS = ("{claude_org_path}", "{worker_dir}")


def _walk(node: Any, fn):
    if isinstance(node, dict):
        return {k: _walk(v, fn) for k, v in node.items()}
    if isinstance(node, list):
        return [_walk(v, fn) for v in node]
    if isinstance(node, str):
        return fn(node)
    return node


def substitute_placeholders(template: dict, mapping: dict[str, str]) -> dict:
    def fn(s: str) -> str:
        out = s
        for k, v in mapping.items():
            out = out.replace(k, v)
        return out
    return _walk(template, fn)


def detect_claude_org_path(current: dict | None) -> str | None:
    if not current:
        return None
    env = (current.get("env") or {})
    val = env.get("CLAUDE_ORG_PATH")
    if isinstance(val, str) and val:
        return val
    # fallback: extract from any hook command of the form `bash "<path>/.hooks/..."`
    hooks = (current.get("hooks") or {})
    for entries in hooks.values():
        for entry in entries or []:
            for sub in (entry.get("hooks") or []):
                cmd = sub.get("command", "")
                m = re.search(r'bash\s+"([^"]+)/\.hooks/', cmd)
                if m:
                    return m.group(1)
    return None


# ---------- merge ----------

def deep_merge(base: dict, overlay: dict) -> dict:
    """Deep-merge overlay onto base.

    - dict: recursively merge keys (overlay wins on scalar conflicts).
    - list: union preserving base order then overlay-only suffix; for lists of
      dicts (hooks), append entries from overlay that are not deep-equal to any
      base entry.
    - scalar: overlay wins.
    """
    if not isinstance(overlay, dict):
        return overlay
    out = dict(base)
    for key, ov in overlay.items():
        if key in out and isinstance(out[key], dict) and isinstance(ov, dict):
            out[key] = deep_merge(out[key], ov)
        elif key in out and isinstance(out[key], list) and isinstance(ov, list):
            out[key] = _merge_lists(out[key], ov)
        else:
            out[key] = ov
    return out


def _merge_lists(base: list, overlay: list) -> list:
    out = list(base)
    for item in overlay:
        if item in out:
            continue
        # for dicts (e.g. hook entries), avoid duplicating equivalent objects
        if isinstance(item, dict) and any(isinstance(b, dict) and b == item for b in out):
            continue
        out.append(item)
    return out


# ---------- diff ----------

def compute_diff(current: dict, target: dict) -> dict:
    """Return added/removed entries (both for permissions.allow/deny and
    top-level keys). Aimed at humans, not at re-applying."""
    cur_allow = set(((current.get("permissions") or {}).get("allow")) or [])
    tgt_allow = set(((target.get("permissions") or {}).get("allow")) or [])
    cur_deny = set(((current.get("permissions") or {}).get("deny")) or [])
    tgt_deny = set(((target.get("permissions") or {}).get("deny")) or [])
    return {
        "allow_added": sorted(tgt_allow - cur_allow),
        "allow_removed": sorted(cur_allow - tgt_allow),
        "deny_added": sorted(tgt_deny - cur_deny),
        "deny_removed": sorted(cur_deny - tgt_deny),
    }


def render_diff(role: str, settings_path: Path, current: dict, target: dict) -> str:
    d = compute_diff(current, target)
    lines = [f"=== {role}: {settings_path} ==="]
    # "no changes" only when allow/deny *and* the rest of the JSON match —
    # env / hooks differences alone (placeholder resolution, override merges)
    # would otherwise produce a misleading "(no changes)" header followed by
    # a non-empty unified diff below.
    if not any(d.values()) and current == target:
        lines.append("  (no changes)")
    for label, items, sign in (
        ("permissions.allow removed", d["allow_removed"], "-"),
        ("permissions.allow added",   d["allow_added"],   "+"),
        ("permissions.deny  removed", d["deny_removed"],  "-"),
        ("permissions.deny  added",   d["deny_added"],    "+"),
    ):
        if items:
            lines.append(f"  {label}:")
            for it in items:
                lines.append(f"    {sign} {it}")
    cur_json = json.dumps(current, indent=2, ensure_ascii=False, sort_keys=True).splitlines()
    tgt_json = json.dumps(target,  indent=2, ensure_ascii=False, sort_keys=True).splitlines()
    udiff = list(difflib.unified_diff(
        cur_json, tgt_json, fromfile="current", tofile="target", lineterm=""
    ))
    if udiff:
        lines.append("  --- full unified diff ---")
        lines.extend("  " + l for l in udiff)
    return "\n".join(lines)


# ---------- write ----------

def backup_path(settings_path: Path) -> Path:
    ts = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    return settings_path.with_name(settings_path.name + f".bak.{ts}")


def write_settings(settings_path: Path, target: dict, *, make_backup: bool) -> Path | None:
    bak: Path | None = None
    if make_backup and settings_path.is_file():
        bak = backup_path(settings_path)
        bak.write_bytes(settings_path.read_bytes())
    text = json.dumps(target, indent=2, ensure_ascii=False) + "\n"
    # Round-trip validation per Issue #88 acceptance criterion.
    json.loads(text)
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    settings_path.write_text(text, encoding="utf-8")
    return bak


# ---------- user_common sandbox merge ----------

def filter_existing_user_dirs(
    candidates: tuple[str, ...] | list[str],
    *,
    home: Path | None = None,
) -> list[str]:
    """Return the subset of ``~``-prefixed candidates whose expanded path is
    an existing directory **and resolves to a realpath inside HOME**.

    The returned entries are the *original* ``~``-prefixed literals -- they
    are what gets written into ``settings.json`` so the file stays portable
    across users. ``home`` is injectable so tests can stand up a temporary
    HOME without monkey-patching ``Path.home``. Non-``~`` and non-directory
    entries are skipped (we never deny things that do not exist; the
    bwrap launcher would treat them as case-A skipped entries anyway).

    **Realpath escape suppression**: on WSL it is common for ``~/.aws`` /
    ``~/.ssh`` to be symlinks pointing at ``/mnt/c/Users/<name>/.aws`` etc.,
    which is outside the sandbox read root and trips a bwrap bootstrap
    failure (case A in the launcher contract). Mirror the claude-org-runtime
    generator's behavior (``suppressOnSymlinkEscape=True`` default in
    ``role_configs_schema.json#$comment_sandbox_anchor``): if the candidate's
    ``Path.resolve()`` lands outside ``home.resolve()`` we drop it here so
    the user_common settings.json never asks the launcher to deny an entry
    it would have to skip anyway. Note: Issue #429 Task C removed
    ``Read(~/.aws/*)`` / ``Read(~/.ssh/*)`` from the project shared
    ``.claude/settings.json``; the only Layer 2 mirrors that survive today
    are inside ``tools/org_extension_schema.json`` ``worker_roles.*``
    templates, which are emitted into per-worker ``settings.local.json`` and
    are likewise unaffected by this filter."""
    base = home if home is not None else Path.home()
    try:
        base_real = base.resolve()
    except OSError:
        base_real = base
    out: list[str] = []
    for entry in candidates:
        if entry.startswith("~/"):
            target = base / entry[2:]
        elif entry == "~":
            target = base
        else:
            # Absolute / relative entries are out of scope for this helper;
            # the merge function will still preserve them if already present.
            continue
        if not target.is_dir():
            continue
        try:
            target_real = target.resolve()
        except OSError:
            # If realpath cannot be computed we conservatively drop the
            # entry rather than risk a bwrap failure on a broken symlink.
            continue
        try:
            target_real.relative_to(base_real)
        except ValueError:
            # Symlink escape: realpath landed outside HOME. Skip to avoid
            # the WSL bwrap bootstrap failure described in
            # docs/sandbox-probe/phase3-bootstrap-policy-design.md §5.
            continue
        out.append(entry)
    return out


def _merge_sandbox_deny(
    settings: dict,
    entries: list[str] | tuple[str, ...],
    *,
    key: str,
) -> dict:
    """Shared pure merger for ``sandbox.filesystem.{key}`` -- the engine
    behind both ``merge_user_common_sandbox_denyread`` and
    ``merge_user_common_sandbox_denywrite``. ``key`` is ``"denyRead"`` or
    ``"denyWrite"``.

    Semantics (identical across the two keys):

    - Existing top-level keys (theme, env, permissions, etc.) are preserved.
    - Existing ``sandbox`` / ``sandbox.filesystem`` siblings (``enabled``,
      ``failIfUnavailable``, the *other* deny list, ``additionalDirectories``,
      etc.) are preserved.
    - Existing list order and entries are preserved; new entries are
      appended in input order, skipping any that already match an existing
      value verbatim. This makes the operation idempotent: re-running on a
      previously-merged file is a no-op.
    - The input is never mutated; nested dicts/lists are shallow-copied
      along the touched spine. Callers can compare ``id`` / ``==`` safely.

    Raises ``ValueError`` if an existing ``sandbox`` / ``sandbox.filesystem``
    is not a JSON object, or the targeted deny list is not a JSON array of
    strings. The caller is expected to abort before touching the file
    rather than silently coerce a malformed shape (which would destroy
    user data).
    """
    sandbox_val = settings.get("sandbox")
    if sandbox_val is not None and not isinstance(sandbox_val, dict):
        raise ValueError(
            f"settings['sandbox'] must be an object or absent, got {type(sandbox_val).__name__}"
        )
    fs_val = sandbox_val.get("filesystem") if isinstance(sandbox_val, dict) else None
    if fs_val is not None and not isinstance(fs_val, dict):
        raise ValueError(
            f"settings['sandbox']['filesystem'] must be an object or absent, got {type(fs_val).__name__}"
        )
    deny_val = fs_val.get(key) if isinstance(fs_val, dict) else None
    if deny_val is not None and not isinstance(deny_val, list):
        raise ValueError(
            f"settings['sandbox']['filesystem']['{key}'] must be an array or absent, got {type(deny_val).__name__}"
        )
    existing: list = list(deny_val) if isinstance(deny_val, list) else []
    # All existing entries must be strings: Claude Code's own bwrap launcher
    # consumes the raw-string form in ~/.claude/settings.json (the structured
    # ``{anchor: ..., path: ...}`` form is internal to claude-org-runtime's
    # worker-settings generator, NOT the user-level surface). If a caller has
    # smuggled a non-string entry in we refuse to merge so downstream set /
    # diff operations on the rendered list never hit ``TypeError`` on an
    # unhashable element, and so the merge cannot accidentally legitimize an
    # entry shape the launcher would reject.
    for i, ex in enumerate(existing):
        if not isinstance(ex, str):
            raise ValueError(
                f"settings['sandbox']['filesystem']['{key}'][{i}] must be a string, got {type(ex).__name__}"
            )

    added = [e for e in entries if e not in existing]
    if not added:
        # No new entries to merge -- return the input unchanged. This keeps
        # the operation a true no-op when none of the candidates apply (or
        # all of them are already present), instead of injecting an empty
        # ``sandbox.filesystem.{key}: []`` block that the user never had.
        # Required so the non-dry-run path matches the dry-run "(no
        # changes)" output (Codex round-2 review, Issue #429 Task B).
        return dict(settings)

    result = dict(settings)
    sandbox = dict(sandbox_val) if isinstance(sandbox_val, dict) else {}
    filesystem = dict(fs_val) if isinstance(fs_val, dict) else {}
    filesystem[key] = existing + added
    sandbox["filesystem"] = filesystem
    result["sandbox"] = sandbox
    return result


def merge_user_common_sandbox_denyread(
    settings: dict,
    entries: list[str] | tuple[str, ...],
) -> dict:
    """Pure: union-merge ``entries`` into ``sandbox.filesystem.denyRead``.
    See ``_merge_sandbox_deny`` for the shared semantics (idempotent,
    additive-only, malformed shape raises ``ValueError``, input never
    mutated)."""
    return _merge_sandbox_deny(settings, entries, key="denyRead")


def merge_user_common_sandbox_denywrite(
    settings: dict,
    entries: list[str] | tuple[str, ...],
) -> dict:
    """Pure: union-merge ``entries`` into ``sandbox.filesystem.denyWrite``.

    Mirrors ``merge_user_common_sandbox_denyread`` -- denyWrite entries
    are *file* literals (e.g. ``~/.claude/settings.json``) rather than
    directories, and the caller is expected **not** to existence-filter
    them: blocking a write is preventive and remains meaningful even
    when the file has not yet been created. Shape validation and the
    idempotent / additive semantics are identical to the denyRead helper.
    """
    return _merge_sandbox_deny(settings, entries, key="denyWrite")


def process_user_common_sandbox(
    *,
    settings_path: Path,
    denyread_candidates: tuple[str, ...] | list[str] = USER_COMMON_SANDBOX_DENYREAD_CANDIDATES,
    denywrite_candidates: tuple[str, ...] | list[str] = USER_COMMON_SANDBOX_DENYWRITE_CANDIDATES,
    home: Path | None = None,
    dry_run: bool,
    no_backup: bool,
) -> int:
    """Drive a user_common sandbox merge against ``settings_path``.

    Applies two idempotent merges in sequence: directory-level
    ``sandbox.filesystem.denyRead`` candidates (existence + realpath-escape
    filtered) followed by file-level ``sandbox.filesystem.denyWrite``
    candidates (preventive deny -- no existence filter; Issue #433).

    Returns a process-style return code (0 on success / no-op; non-zero on
    malformed JSON). When ``settings_path`` does not exist the file is
    created with only the ``sandbox`` block populated -- never invents
    other top-level keys."""
    current: dict
    if settings_path.is_file():
        try:
            current = json.loads(settings_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(
                f"[org_setup_prune] user_common: current settings.json is invalid JSON ({exc}); aborting before any write.",
                file=sys.stderr,
            )
            return 2
        if not isinstance(current, dict):
            print(
                f"[org_setup_prune] user_common: top level of {settings_path} must be a JSON object, got {type(current).__name__}; aborting.",
                file=sys.stderr,
            )
            return 2
    else:
        current = {}

    existing_read_entries = filter_existing_user_dirs(denyread_candidates, home=home)
    try:
        target = merge_user_common_sandbox_denyread(current, existing_read_entries)
        target = merge_user_common_sandbox_denywrite(target, denywrite_candidates)
    except ValueError as exc:
        print(
            f"[org_setup_prune] user_common: {settings_path} has malformed sandbox shape: {exc}; aborting.",
            file=sys.stderr,
        )
        return 2

    if dry_run:
        # In dry-run we always render the report, even on no-op, so the
        # operator can see which candidates were skipped (missing dir /
        # symlink-escape) and judge whether the result is correct.
        print(
            render_user_common_diff(
                settings_path,
                current,
                target,
                denyread_candidates,
                existing_read_entries,
                denywrite_candidates,
            )
        )
        return 0

    if target == current:
        msg = (
            f"[org_setup_prune] user_common: {settings_path} already has all "
            "applicable sandbox.filesystem.denyRead / denyWrite entries; no changes."
        )
        print(msg)
        return 0

    bak = write_settings(settings_path, target, make_backup=not no_backup)
    added_read = _added_in_append_order(_safe_deny_list(current, "denyRead"), _safe_deny_list(target, "denyRead"))
    added_write = _added_in_append_order(_safe_deny_list(current, "denyWrite"), _safe_deny_list(target, "denyWrite"))
    fragments: list[str] = []
    if added_read:
        fragments.append(f"denyRead {added_read}")
    if added_write:
        fragments.append(f"denyWrite {added_write}")
    added_summary = "; added " + ", ".join(fragments) if fragments else ""
    print(
        f"[org_setup_prune] user_common: wrote {settings_path}"
        + (f" (backup: {bak.name})" if bak else "")
        + added_summary
    )
    return 0


def _safe_deny_list(settings: dict, key: str) -> list[str]:
    """Return a copy of ``sandbox.filesystem.{key}`` from ``settings``,
    defaulting to an empty list when any spine node is missing. ``key`` is
    ``"denyRead"`` or ``"denyWrite"``."""
    return list(((settings.get("sandbox") or {}).get("filesystem") or {}).get(key) or [])


def _safe_deny_read(settings: dict) -> list[str]:
    """Backwards-compatible shim around ``_safe_deny_list`` (Issue #429
    Task B). Retained because external callers / tests may import the
    symbol directly."""
    return _safe_deny_list(settings, "denyRead")


def _added_in_append_order(current: list[str], target: list[str]) -> list[str]:
    """Return the suffix of ``target`` that the merger appended on top of
    ``current`` -- preserving the input-append order the merger advertises
    (i.e., the order the user will see in the file). Used for both
    denyRead and denyWrite diffs."""
    cur_set = set(current)
    return [e for e in target if e not in cur_set]


def render_user_common_diff(
    settings_path: Path,
    current: dict,
    target: dict,
    denyread_candidates: tuple[str, ...] | list[str],
    existing_read_entries: list[str],
    denywrite_candidates: tuple[str, ...] | list[str] = (),
) -> str:
    added_read = _added_in_append_order(_safe_deny_list(current, "denyRead"), _safe_deny_list(target, "denyRead"))
    added_write = _added_in_append_order(_safe_deny_list(current, "denyWrite"), _safe_deny_list(target, "denyWrite"))
    skipped_missing = [c for c in denyread_candidates if c not in existing_read_entries]
    lines = [f"=== user_common: {settings_path} ==="]
    if not added_read and not added_write:
        lines.append("  (no changes)")
    if added_read:
        lines.append("  sandbox.filesystem.denyRead added:")
        for it in added_read:
            lines.append(f"    + {it}")
    if added_write:
        lines.append("  sandbox.filesystem.denyWrite added:")
        for it in added_write:
            lines.append(f"    + {it}")
    if skipped_missing:
        # These include both non-existent directories AND symlink-escape
        # entries (the latter are common on WSL where ``~/.aws`` /
        # ``~/.ssh`` may resolve to ``/mnt/c/...``). denyWrite candidates
        # are *not* existence-checked (preventive deny, Issue #433) so they
        # never appear in this list.
        lines.append("  skipped denyRead (directory missing or resolves outside HOME):")
        for it in skipped_missing:
            lines.append(f"    - {it}")
    return "\n".join(lines)


# ---------- driver ----------

def build_target(
    role: str,
    template: dict,
    current: dict | None,
    override: dict | None,
    *,
    claude_org_path: str | None,
    worker_dir: str | None,
) -> dict:
    mapping: dict[str, str] = {}
    if claude_org_path:
        mapping["{claude_org_path}"] = claude_org_path
    if worker_dir:
        mapping["{worker_dir}"] = worker_dir
    resolved = substitute_placeholders(template, mapping) if mapping else template
    # Detect placeholders that survived: signal misconfiguration.
    leftover = _find_placeholders(resolved)
    if leftover:
        raise SystemExit(
            f"[org_setup_prune] role={role}: unresolved placeholders {sorted(leftover)} "
            "(pass --claude-org-path or run inside a configured worktree so the value can be inferred from existing settings)."
        )
    if override:
        return deep_merge(resolved, override)
    return resolved


def _find_placeholders(node: Any) -> set[str]:
    found: set[str] = set()

    def visit(n: Any) -> None:
        if isinstance(n, dict):
            for v in n.values():
                visit(v)
        elif isinstance(n, list):
            for v in n:
                visit(v)
        elif isinstance(n, str):
            for ph in PLACEHOLDER_KEYS:
                if ph in n:
                    found.add(ph)

    visit(node)
    return found


def _validate_override_shape(data: object) -> str | None:
    """Return None when the override file is structurally usable, else an
    error message. Catches user mistakes (top-level array, scalar permissions,
    non-string allow entries) before they reach deep_merge / validate_config
    where they would crash with an opaque AttributeError."""
    if not isinstance(data, dict):
        return f"top level must be a JSON object, got {type(data).__name__}"
    perms = data.get("permissions")
    if perms is not None and not isinstance(perms, dict):
        return f"'permissions' must be an object, got {type(perms).__name__}"
    if isinstance(perms, dict):
        for key in ("allow", "deny"):
            v = perms.get(key)
            if v is None:
                continue
            if not isinstance(v, list) or not all(isinstance(x, str) for x in v):
                return f"'permissions.{key}' must be a list of strings"
    env = data.get("env")
    if env is not None and not isinstance(env, dict):
        return f"'env' must be an object, got {type(env).__name__}"
    return None


def _validate_target_safety(role: str, role_schema: dict, global_schema: dict, target: dict) -> list[str]:
    """Re-run the safety subset of check_role_configs against the merged target
    so an override file cannot smuggle in forbidden / role-disallowed allow
    entries past the writer. Returns ERROR messages; empty list = safe.
    Closed-world unknown-allow checks are intentionally skipped here -- the
    override file IS the user-sanctioned escape hatch for those, and the
    on-disk checker subtracts them. Forbidden / disallow patterns remain
    enforced because the safety contract documents them as non-bypassable.
    """
    findings = _check.validate_config(
        f"prune[{role}]", role, target, role_schema, global_schema,
        extra_allowed=set((target.get("permissions") or {}).get("allow") or []),
    )
    # Keep only the categories that codify the safety contract; required_*
    # missing-entry findings are not write-blocking (they would be a template
    # bug surfaced by check_role_configs separately).
    blockers: list[str] = []
    for f in findings:
        msg = f.message
        if (
            "forbidden wide allow entry" in msg
            or "forbidden allow entry" in msg
            or "role contract violation" in msg
        ):
            blockers.append(f.format())
    return blockers


def process_role(
    role: str,
    schema: dict,
    permissions_md_text: str,
    *,
    root: Path,
    dry_run: bool,
    claude_org_path_arg: str | None,
    no_backup: bool,
) -> int:
    blocks = extract_role_blocks(permissions_md_text, schema["roles"])
    template = blocks.get(role)
    if template is None:
        print(f"[org_setup_prune] role={role}: no template found in permissions.md", file=sys.stderr)
        return 2

    settings_path = role_settings_path(root, role)
    current = None
    if settings_path.is_file():
        try:
            current = json.loads(settings_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(f"[org_setup_prune] role={role}: current settings.local.json is invalid JSON ({exc}); aborting before any write.", file=sys.stderr)
            return 2

    ov_path = override_path(settings_path)
    override = None
    if ov_path.is_file():
        try:
            override = json.loads(ov_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(f"[org_setup_prune] role={role}: override file invalid JSON: {ov_path} ({exc}); aborting.", file=sys.stderr)
            return 2
        shape_err = _validate_override_shape(override)
        if shape_err is not None:
            print(f"[org_setup_prune] role={role}: override file has invalid shape: {ov_path} ({shape_err}); aborting.", file=sys.stderr)
            return 2

    cop = claude_org_path_arg or detect_claude_org_path(current)
    role_schema = schema["roles"].get(role, {})
    try:
        target = build_target(
            role, template, current, override,
            claude_org_path=cop, worker_dir=None,
        )
    except SystemExit as exc:
        # build_target raises SystemExit with a human-readable message when the
        # placeholder cannot be resolved; surface it as a non-zero rc instead
        # of bubbling up so callers (incl. tests) get a normal return.
        print(str(exc), file=sys.stderr)
        return 2

    safety_blockers = _validate_target_safety(role, role_schema, schema.get("global", {}), target)
    if safety_blockers:
        print(
            f"[org_setup_prune] role={role}: refusing to write -- merged target violates the safety contract "
            "(forbidden wide allow / role disallow). Fix the override file and retry.",
            file=sys.stderr,
        )
        for line in safety_blockers:
            print("  " + line, file=sys.stderr)
        return 2

    if dry_run:
        if current is None:
            print(f"=== {role}: {settings_path} ===\n  (no current file; would create with template{' + override' if override else ''})")
        else:
            print(render_diff(role, settings_path, current, target))
        if override:
            print(f"  [override] merged from {ov_path}")
        return 0

    bak = write_settings(settings_path, target, make_backup=not no_backup)
    print(f"[org_setup_prune] role={role}: wrote {settings_path}" + (f" (backup: {bak.name})" if bak else ""))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Prune (fully rewrite) per-role settings.local.json from permissions.md.",
    )
    parser.add_argument("--role", choices=PRUNABLE_ROLES, default=None)
    parser.add_argument("--all", action="store_true", help=f"Apply to every prunable role: {', '.join(PRUNABLE_ROLES)}.")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--permissions-md", type=Path, default=DEFAULT_PERMISSIONS_MD)
    parser.add_argument(
        "--claude-org-path",
        default=None,
        help="Absolute path used to substitute {claude_org_path} placeholders in the dispatcher template. Inferred from existing settings.local.json env when present.",
    )
    parser.add_argument(
        "--no-backup",
        action="store_true",
        help="Do not write a timestamped .bak file before overwriting (default: backup is written).",
    )
    parser.add_argument(
        "--user-common-sandbox",
        action="store_true",
        help="Union-merge sensitive credential directory denyRead entries AND a denyWrite entry "
             "for ~/.claude/settings.json into the user-level ~/.claude/settings.json sandbox "
             "block (idempotent, ~-prefixed; denyRead candidates existence-checked, denyWrite "
             "candidates always merged as preventive deny). Does NOT rewrite other keys. "
             "See Issue #429 (Task B/C, denyRead) and Issue #433 (denyWrite migration).",
    )
    parser.add_argument(
        "--user-common-settings-path",
        type=Path,
        default=None,
        help="Override the user_common settings.json path (default: ~/.claude/settings.json). "
             "Primarily for tests.",
    )
    parser.add_argument(
        "--user-common-home",
        type=Path,
        default=None,
        help="Override the HOME directory used for the existence + realpath-escape check "
             "of --user-common-sandbox candidates. Primarily for tests. When omitted, the "
             "real HOME is used (or, if --user-common-settings-path points at a path of the "
             "form <DIR>/.claude/settings.json, <DIR> is used so tests can supply only the "
             "settings path).",
    )
    args = parser.parse_args(argv)

    if not args.role and not args.all and not args.user_common_sandbox:
        parser.error("specify --role <name>, --all, or --user-common-sandbox")

    rc = 0

    if args.role or args.all:
        schema = load_schema(args.schema)
        permissions_md_text = args.permissions_md.read_text(encoding="utf-8")
        roles = list(PRUNABLE_ROLES) if args.all else [args.role]
        for role in roles:
            r = process_role(
                role, schema, permissions_md_text,
                root=args.root,
                dry_run=args.dry_run,
                claude_org_path_arg=args.claude_org_path,
                no_backup=args.no_backup,
            )
            rc = rc or r

    if args.user_common_sandbox:
        settings_path = args.user_common_settings_path or DEFAULT_USER_COMMON_SETTINGS_PATH
        home = args.user_common_home
        if home is None and args.user_common_settings_path is not None:
            # Auto-derive HOME from a ``<DIR>/.claude/settings.json``-shaped
            # override so a test that supplies only --user-common-settings-path
            # exercises the existence + realpath-escape check against the
            # temp tree, not the operator's real HOME.
            p = args.user_common_settings_path
            if p.name == "settings.json" and p.parent.name == ".claude":
                home = p.parent.parent
        r = process_user_common_sandbox(
            settings_path=settings_path,
            home=home,
            dry_run=args.dry_run,
            no_backup=args.no_backup,
        )
        rc = rc or r

    return rc


if __name__ == "__main__":
    raise SystemExit(main())
