#!/usr/bin/env python3
"""org-setup --prune: rewrite role settings.local.json from permissions.md.

Background (Issue #88): the additive ``/org-setup`` cannot remove stale or
broadened entries from ``settings.local.json``. This tool rewrites the file
from the role template embedded in
``.claude/skills/org-setup/references/permissions.md`` (the human-readable
projection of ``tools/role_configs_schema.json``) so drift is fully resolved.

User-extension protection (Issue #88 option A): if a sibling
``settings.local.override.json`` exists, its contents are deep-merged on top
of the template. Users put bespoke entries there once; the prune tool never
touches it, so personal customizations survive every rewrite.

Targets: secretary / dispatcher / curator. (user_common lives at
``~/.claude/settings.json``; worker is generated by org-delegate -- both out
of scope here.)

Usage:
    py -3 tools/org_setup_prune.py --role secretary --dry-run
    py -3 tools/org_setup_prune.py --role dispatcher
    py -3 tools/org_setup_prune.py --all --dry-run
"""

from __future__ import annotations

import argparse
import datetime as _dt
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_role_configs as _check  # noqa: E402  -- reuse validate_config

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SCHEMA = REPO_ROOT / "tools" / "role_configs_schema.json"
DEFAULT_PERMISSIONS_MD = (
    REPO_ROOT
    / ".claude"
    / "skills"
    / "org-setup"
    / "references"
    / "permissions.md"
)

PRUNABLE_ROLES = ("secretary", "dispatcher", "curator")


def load_schema(path: Path) -> dict:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def extract_role_blocks(md_text: str, roles: dict) -> dict[str, dict | None]:
    """Mirror of check_role_configs.extract_role_blocks (kept inline to avoid a
    cross-module import at script invocation time)."""
    results: dict[str, dict | None] = {}
    sections = re.split(r"(?m)^## ", md_text)
    for role_name, role_def in roles.items():
        marker = role_def.get("docs_section")
        if not marker:
            continue
        block = None
        for section in sections[1:]:
            if marker in section.splitlines()[0]:
                m = re.search(r"```json\n(.*?)\n```", section, re.DOTALL)
                if m:
                    block = json.loads(m.group(1))
                break
        results[role_name] = block
    return results


def role_settings_path(root: Path, role: str) -> Path:
    if role == "secretary":
        return root / ".claude" / "settings.local.json"
    if role == "dispatcher":
        return root / ".dispatcher" / ".claude" / "settings.local.json"
    if role == "curator":
        return root / ".curator" / ".claude" / "settings.local.json"
    raise ValueError(f"unsupported role for prune: {role!r}")


def override_path(settings_path: Path) -> Path:
    return settings_path.with_name("settings.local.override.json")


# ---------- placeholder resolution ----------

PLACEHOLDER_KEYS = ("{claude_org_path}", "{worker_dir}")


def _walk(node: Any, fn):
    if isinstance(node, dict):
        return {k: _walk(v, fn) for k, v in node.items()}
    if isinstance(node, list):
        return [_walk(v, fn) for v in node]
    if isinstance(node, str):
        return fn(node)
    return node


def substitute_placeholders(template: dict, mapping: dict[str, str]) -> dict:
    def fn(s: str) -> str:
        out = s
        for k, v in mapping.items():
            out = out.replace(k, v)
        return out
    return _walk(template, fn)


def detect_claude_org_path(current: dict | None) -> str | None:
    if not current:
        return None
    env = (current.get("env") or {})
    val = env.get("CLAUDE_ORG_PATH")
    if isinstance(val, str) and val:
        return val
    # fallback: extract from any hook command of the form `bash "<path>/.hooks/..."`
    hooks = (current.get("hooks") or {})
    for entries in hooks.values():
        for entry in entries or []:
            for sub in (entry.get("hooks") or []):
                cmd = sub.get("command", "")
                m = re.search(r'bash\s+"([^"]+)/\.hooks/', cmd)
                if m:
                    return m.group(1)
    return None


# ---------- merge ----------

def deep_merge(base: dict, overlay: dict) -> dict:
    """Deep-merge overlay onto base.

    - dict: recursively merge keys (overlay wins on scalar conflicts).
    - list: union preserving base order then overlay-only suffix; for lists of
      dicts (hooks), append entries from overlay that are not deep-equal to any
      base entry.
    - scalar: overlay wins.
    """
    if not isinstance(overlay, dict):
        return overlay
    out = dict(base)
    for key, ov in overlay.items():
        if key in out and isinstance(out[key], dict) and isinstance(ov, dict):
            out[key] = deep_merge(out[key], ov)
        elif key in out and isinstance(out[key], list) and isinstance(ov, list):
            out[key] = _merge_lists(out[key], ov)
        else:
            out[key] = ov
    return out


def _merge_lists(base: list, overlay: list) -> list:
    out = list(base)
    for item in overlay:
        if item in out:
            continue
        # for dicts (e.g. hook entries), avoid duplicating equivalent objects
        if isinstance(item, dict) and any(isinstance(b, dict) and b == item for b in out):
            continue
        out.append(item)
    return out


# ---------- diff ----------

def compute_diff(current: dict, target: dict) -> dict:
    """Return added/removed entries (both for permissions.allow/deny and
    top-level keys). Aimed at humans, not at re-applying."""
    cur_allow = set(((current.get("permissions") or {}).get("allow")) or [])
    tgt_allow = set(((target.get("permissions") or {}).get("allow")) or [])
    cur_deny = set(((current.get("permissions") or {}).get("deny")) or [])
    tgt_deny = set(((target.get("permissions") or {}).get("deny")) or [])
    return {
        "allow_added": sorted(tgt_allow - cur_allow),
        "allow_removed": sorted(cur_allow - tgt_allow),
        "deny_added": sorted(tgt_deny - cur_deny),
        "deny_removed": sorted(cur_deny - tgt_deny),
    }


def render_diff(role: str, settings_path: Path, current: dict, target: dict) -> str:
    d = compute_diff(current, target)
    lines = [f"=== {role}: {settings_path} ==="]
    # "no changes" only when allow/deny *and* the rest of the JSON match —
    # env / hooks differences alone (placeholder resolution, override merges)
    # would otherwise produce a misleading "(no changes)" header followed by
    # a non-empty unified diff below.
    if not any(d.values()) and current == target:
        lines.append("  (no changes)")
    for label, items, sign in (
        ("permissions.allow removed", d["allow_removed"], "-"),
        ("permissions.allow added",   d["allow_added"],   "+"),
        ("permissions.deny  removed", d["deny_removed"],  "-"),
        ("permissions.deny  added",   d["deny_added"],    "+"),
    ):
        if items:
            lines.append(f"  {label}:")
            for it in items:
                lines.append(f"    {sign} {it}")
    cur_json = json.dumps(current, indent=2, ensure_ascii=False, sort_keys=True).splitlines()
    tgt_json = json.dumps(target,  indent=2, ensure_ascii=False, sort_keys=True).splitlines()
    udiff = list(difflib.unified_diff(
        cur_json, tgt_json, fromfile="current", tofile="target", lineterm=""
    ))
    if udiff:
        lines.append("  --- full unified diff ---")
        lines.extend("  " + l for l in udiff)
    return "\n".join(lines)


# ---------- write ----------

def backup_path(settings_path: Path) -> Path:
    ts = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    return settings_path.with_name(settings_path.name + f".bak.{ts}")


def write_settings(settings_path: Path, target: dict, *, make_backup: bool) -> Path | None:
    bak: Path | None = None
    if make_backup and settings_path.is_file():
        bak = backup_path(settings_path)
        bak.write_bytes(settings_path.read_bytes())
    text = json.dumps(target, indent=2, ensure_ascii=False) + "\n"
    # Round-trip validation per Issue #88 acceptance criterion.
    json.loads(text)
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    settings_path.write_text(text, encoding="utf-8")
    return bak


# ---------- driver ----------

def build_target(
    role: str,
    template: dict,
    current: dict | None,
    override: dict | None,
    *,
    claude_org_path: str | None,
    worker_dir: str | None,
) -> dict:
    mapping: dict[str, str] = {}
    if claude_org_path:
        mapping["{claude_org_path}"] = claude_org_path
    if worker_dir:
        mapping["{worker_dir}"] = worker_dir
    resolved = substitute_placeholders(template, mapping) if mapping else template
    # Detect placeholders that survived: signal misconfiguration.
    leftover = _find_placeholders(resolved)
    if leftover:
        raise SystemExit(
            f"[org_setup_prune] role={role}: unresolved placeholders {sorted(leftover)} "
            "(pass --claude-org-path or run inside a configured worktree so the value can be inferred from existing settings)."
        )
    if override:
        return deep_merge(resolved, override)
    return resolved


def _find_placeholders(node: Any) -> set[str]:
    found: set[str] = set()

    def visit(n: Any) -> None:
        if isinstance(n, dict):
            for v in n.values():
                visit(v)
        elif isinstance(n, list):
            for v in n:
                visit(v)
        elif isinstance(n, str):
            for ph in PLACEHOLDER_KEYS:
                if ph in n:
                    found.add(ph)

    visit(node)
    return found


def _validate_override_shape(data: object) -> str | None:
    """Return None when the override file is structurally usable, else an
    error message. Catches user mistakes (top-level array, scalar permissions,
    non-string allow entries) before they reach deep_merge / validate_config
    where they would crash with an opaque AttributeError."""
    if not isinstance(data, dict):
        return f"top level must be a JSON object, got {type(data).__name__}"
    perms = data.get("permissions")
    if perms is not None and not isinstance(perms, dict):
        return f"'permissions' must be an object, got {type(perms).__name__}"
    if isinstance(perms, dict):
        for key in ("allow", "deny"):
            v = perms.get(key)
            if v is None:
                continue
            if not isinstance(v, list) or not all(isinstance(x, str) for x in v):
                return f"'permissions.{key}' must be a list of strings"
    env = data.get("env")
    if env is not None and not isinstance(env, dict):
        return f"'env' must be an object, got {type(env).__name__}"
    return None


def _validate_target_safety(role: str, role_schema: dict, global_schema: dict, target: dict) -> list[str]:
    """Re-run the safety subset of check_role_configs against the merged target
    so an override file cannot smuggle in forbidden / role-disallowed allow
    entries past the writer. Returns ERROR messages; empty list = safe.
    Closed-world unknown-allow checks are intentionally skipped here -- the
    override file IS the user-sanctioned escape hatch for those, and the
    on-disk checker subtracts them. Forbidden / disallow patterns remain
    enforced because the safety contract documents them as non-bypassable.
    """
    findings = _check.validate_config(
        f"prune[{role}]", role, target, role_schema, global_schema,
        extra_allowed=set((target.get("permissions") or {}).get("allow") or []),
    )
    # Keep only the categories that codify the safety contract; required_*
    # missing-entry findings are not write-blocking (they would be a template
    # bug surfaced by check_role_configs separately).
    blockers: list[str] = []
    for f in findings:
        msg = f.message
        if (
            "forbidden wide allow entry" in msg
            or "forbidden allow entry" in msg
            or "role contract violation" in msg
        ):
            blockers.append(f.format())
    return blockers


def process_role(
    role: str,
    schema: dict,
    permissions_md_text: str,
    *,
    root: Path,
    dry_run: bool,
    claude_org_path_arg: str | None,
    no_backup: bool,
) -> int:
    blocks = extract_role_blocks(permissions_md_text, schema["roles"])
    template = blocks.get(role)
    if template is None:
        print(f"[org_setup_prune] role={role}: no template found in permissions.md", file=sys.stderr)
        return 2

    settings_path = role_settings_path(root, role)
    current = None
    if settings_path.is_file():
        try:
            current = json.loads(settings_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(f"[org_setup_prune] role={role}: current settings.local.json is invalid JSON ({exc}); aborting before any write.", file=sys.stderr)
            return 2

    ov_path = override_path(settings_path)
    override = None
    if ov_path.is_file():
        try:
            override = json.loads(ov_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(f"[org_setup_prune] role={role}: override file invalid JSON: {ov_path} ({exc}); aborting.", file=sys.stderr)
            return 2
        shape_err = _validate_override_shape(override)
        if shape_err is not None:
            print(f"[org_setup_prune] role={role}: override file has invalid shape: {ov_path} ({shape_err}); aborting.", file=sys.stderr)
            return 2

    cop = claude_org_path_arg or detect_claude_org_path(current)
    role_schema = schema["roles"].get(role, {})
    try:
        target = build_target(
            role, template, current, override,
            claude_org_path=cop, worker_dir=None,
        )
    except SystemExit as exc:
        # build_target raises SystemExit with a human-readable message when the
        # placeholder cannot be resolved; surface it as a non-zero rc instead
        # of bubbling up so callers (incl. tests) get a normal return.
        print(str(exc), file=sys.stderr)
        return 2

    safety_blockers = _validate_target_safety(role, role_schema, schema.get("global", {}), target)
    if safety_blockers:
        print(
            f"[org_setup_prune] role={role}: refusing to write -- merged target violates the safety contract "
            "(forbidden wide allow / role disallow). Fix the override file and retry.",
            file=sys.stderr,
        )
        for line in safety_blockers:
            print("  " + line, file=sys.stderr)
        return 2

    if dry_run:
        if current is None:
            print(f"=== {role}: {settings_path} ===\n  (no current file; would create with template{' + override' if override else ''})")
        else:
            print(render_diff(role, settings_path, current, target))
        if override:
            print(f"  [override] merged from {ov_path}")
        return 0

    bak = write_settings(settings_path, target, make_backup=not no_backup)
    print(f"[org_setup_prune] role={role}: wrote {settings_path}" + (f" (backup: {bak.name})" if bak else ""))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Prune (fully rewrite) per-role settings.local.json from permissions.md.",
    )
    parser.add_argument("--role", choices=PRUNABLE_ROLES, default=None)
    parser.add_argument("--all", action="store_true", help=f"Apply to every prunable role: {', '.join(PRUNABLE_ROLES)}.")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--permissions-md", type=Path, default=DEFAULT_PERMISSIONS_MD)
    parser.add_argument(
        "--claude-org-path",
        default=None,
        help="Absolute path used to substitute {claude_org_path} placeholders in the dispatcher template. Inferred from existing settings.local.json env when present.",
    )
    parser.add_argument(
        "--no-backup",
        action="store_true",
        help="Do not write a timestamped .bak file before overwriting (default: backup is written).",
    )
    args = parser.parse_args(argv)

    if not args.role and not args.all:
        parser.error("specify --role <name> or --all")

    schema = load_schema(args.schema)
    permissions_md_text = args.permissions_md.read_text(encoding="utf-8")

    roles = list(PRUNABLE_ROLES) if args.all else [args.role]
    rc = 0
    for role in roles:
        r = process_role(
            role, schema, permissions_md_text,
            root=args.root,
            dry_run=args.dry_run,
            claude_org_path_arg=args.claude_org_path,
            no_backup=args.no_backup,
        )
        rc = rc or r
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
